### ISSUE TITLE
Attribute Substitution Loophole with Battlefield Retribution (formerly Battlefield Reflexes)

### ISSUE THREAD

**Issue by brianfeister** [openlegend/core-rules#448] opened 2017-07-17 17:29 UTC
As written, `Attribute Substitution I` creates a loophole that allows `Skill Specialization` and `Defensive Reflexes` to be used for Defend actions, thereby, granting you the equivalent of `Attack Specialization` at a much lower cost. 

Let's fix this.

**EDIT**: the reason this is important is because `Sentinel` already threatens to make "Defend build" characters VERY powerful, cheating your way into the equivalent of `Attack Specialization` I think basically puts us "over the line" in terms of how problematic this loophole is.

Note that I saw @buildanddie and @jvango or someone discussing this being a "known issue" on Github. While I hate to re-open the Core Rules for discussion, I'd also rather not ship with known bugs, and we have some extra time due to my change in anticipated schedule around Amaurea's Dawn print timeframe.

**Comment by brianfeister** [comment] 2017-07-17 17:30
Point being @BuildAndDie and @JVanGo, please let moderators know that very obvious bugs like this one should still be surfaced for discussion with me. Just don't assume that I will see it if it's in Discord.

**Comment by oconnor0** [comment] 2017-07-17 17:34
`Defensive Reflexes` also allows `Attack Specialization` equivalent for lower cost (but only for Defend actions). `Skill Specialization` allows that and more - with or without `Attribute Substitution I`.

**Comment by brianfeister** [comment] 2017-07-17 17:36
Thanks @oconnor0, I've added `Defensive Reflexes` to my original description to account for the problem in multiple places.

**Comment by oconnor0** [comment] 2017-07-17 17:40
I assumed it was cheaper because it was a limited version and only can deal damage with `Battlefield Retribution`.

Also `Skill Specialization` and `Defensive Reflexes` allow stacking advantage on Defend actions - beyond advantage 9.

**Comment by brianfeister** [comment] 2017-07-17 17:59
> Also Skill Specialization and Defensive Reflexes allow stacking advantage on Defend actions - beyond advantage 9.

That's fine

**Comment by JVanGo** [comment] 2017-07-17 20:44
@brianfeister This is the first time I've heard of this interaction. I don't know though what attribute substitution adds to that equation. I don't even know how you picked that up, because I don't remember seeing anything like this on Discord or in the forums.

**Comment by brianfeister** [comment] 2017-07-17 20:48
I saw @buildanddie mention it in Discord

**Comment by JVanGo** [comment] 2017-07-17 21:07
I found it. It seemed to have been a part of a greater discussion about skill specialisation and its limitations (like can you use it for initiative, etc.).

**Comment by oconnor0** [comment] 2017-07-17 21:26
I believe this gets used as:

At level 1, Perception 5:

`Attribute Substitution I` (Perception to Agility)
`Battlefield Retribution`
`Skill Specialization I` (Perception)

Defend actions with Agility deal damage with `Battlefield Retribution` and have advantage 1 from `Skill Specialization I` (Perception) because `Attribute Substitution I` uses the primary attribute in place of the secondary. This also gives advantage on initiative and Perception rolls to avoid surprise. Add `Sentinel` and more tiers of `Skill Specialization` (Perception) to further focus.

**Comment by BuildAndDie** [comment] 2017-07-18 02:13
I honestly did see it as an issue when I was just talking about it... yesterday I guess.

Note I just got done driving for 10 hours to get to Mexico and just got situated at the place I will be training people at, so my mind might not be firing on all cylinders.

But yeah, I didn't necessarily see it as an issue when I was first discussing it with... someone, maybe oconnor?

The other thing that I was part of a conversation with was Skill Specialization (Agility) vs Lightning Reflexes. In that Skill Specialization (Agility) was a gray'ish area in regards to Initiative. Technically Initiative isn't an attack roll or bane or boon invocation.

I think most of these issues all revolve around this:

Originally it was (or was discussed to be) worded as "Combat" vs "Non-Combat". At least in regards to Attribute Sub I. But there was the loophole that you could cast boons, so it was further clarified.

Plus Attack Specialization didn't want wording of "Combat" b/c you could still do perception rolls IN combat, and that made sense.

So, based on what I am reading:

1) you don't want Attribute Sub Tier 1 to be able to do Interrupt actions.

and I think that fixes everything else, b/c the attack specialization is just b/c of defend interrupt. So, just add another bullet point under Tier 1 that says:

Can not be used for Interrupt Actions.

That should fix... everything?

Then the next question is, should Skill Specialization (Agility) be able to help out your Initative roll. If that is also fine, then yeah,  just the thing above fixes it, right?

**Comment by oconnor0** [comment] 2017-07-18 02:35
The above would still allow Skill Specialization to apply to interrupt actions.

**Comment by istabosz** [comment] 2017-07-18 02:45
I don't necessarily like the idea of eliminating all interrupt actions from skill specialization. I think if the problem is defend actions, than we just include that in the list of exceptions. I think initiative should probably be excluded as well, as that's what we've got Lightning Reflexes for, and I don't think boosting initiative is in the spirit of Skill Specialization. 

Proposed fix:

_Choose one attribute. Any time you make a roll using the chosen attribute that is not for initiative, attacks, invocations, or the defend action, you gain advantage 1 on the roll per tier of this feat you possess for that attribute._

**Comment by BuildAndDie** [comment] 2017-07-18 02:51
@oconnor0 Brian already stated that Skill Specialization and Defensive Reflexes overlapping was fine above, that's why I didn't address it.

@istabosz I don't think the issue is Skill Specialization at all, and @brianfeister seemed fine with Skill specialization being used for defend interupt as well.

The issue revolved around Attribute Sub Teir 1 being used to do Interrupts, hence my suggestion to exclude Interrupt Actions in the Tier 1 list.

**Comment by oconnor0** [comment] 2017-07-18 03:03
@BuildAndDie If the issue is really just `Attribute Substitution I` being used for defend actions, how about changing the first bullet under Tier 1 to:

- Making non-attack, non-defend, non-invocation action rolls

That's the smallest tweak I can think of that still allows `Attribute Substitution I` to be used for improvised actions.

**Comment by istabosz** [comment] 2017-07-18 03:11
Ahh, I read Brians 's comment as just saying that it was fine to go beyond Advantage 9.

@brianfeister Can you confirm that you are okay with skill specialization affecting Defend actions? That still seems like a loophole around Attack Specialization to me.

**Comment by BuildAndDie** [comment] 2017-07-18 03:13
@oconnor0 ummm for me it was taking out ALL interrupt from Attribute Sub I, as improvised usually are going to be invocation rolls anyways.

so non-interrupt makes more sense to me. Why NOT allow defend, but DO allow improvise?

**Comment by oconnor0** [comment] 2017-07-18 03:59
@BuildAndDie Right, I recognize that. There was some disagreement about the issue and so I figured I'd suggest something that met what @istabosz suggested and dealt with part of what you were addressing.

I could see an improvised action as also being something like grabbing someone's arm as they are falling which would not be an invocation as far as I can tell. I was also going to say administering a potion but unless you're rolling to see if you can get to them in time, the potion is just a heal invocation.

Defend allows for dealing damage with Battlefield Retribution. Improvise does not allow dealing damage.

**Comment by brianfeister** [comment] 2017-07-18 04:17
Locking the thread to quiet things down. @istabosz you can still comment.

Resolution:

1. Skill Specialization should not benefit Defend actions
1. Skill Specialization should not benefit Initiative
1. I'm fine with advantage being stackable above 9 via multiple disparate feats

I think @istabosz fixed it just fine. Is there anything discussed which I didn't respond to in my points above?

```
Choose one attribute. Any time you make a roll using the chosen attribute that is not for initiative, attacks, invocations, or the defend action, you gain advantage 1 on the roll per tier of this feat you possess for that attribute.
```

**Comment by istabosz** [comment] 2017-07-18 13:38
I think the only other thing that needs fixing is being able to use Attribute Substitution I for defend actions. In which case I think @oconnor0 's suggestion works, changing the first bullet point in tier 1 to...

- Making non-attack, non-defend, non-invocation action rolls

**Comment by istabosz** [comment] 2017-08-07 16:07
Fixed these issues with the following:

https://github.com/openlegend/core-rules/commit/edca7ad1d5f34edbb18ed18c43efbe3eeb703e59
https://github.com/openlegend/core-rules/commit/214511aa60751e8887d7ee6103e4f36ebcdfaaeb

**Comment by istabosz** [comment] 2017-08-07 17:01
Mistakenly updated the .yml at first. These have been addressed in the .md here:
https://github.com/openlegend/core-rules/commit/3604626ded9938201d9d22b50fd1ed97c44b37c1
https://github.com/openlegend/core-rules/commit/6e0beab1b4d08517cbcc07daa42eff968da21490

**Comment by brianfeister** [comment] 2017-08-30 04:08
👍

**Closed** 2017-10-05 01:53 UTC
Labels: _web
